
#General Config Section
[general]
	#The Client ID of the Discord App to use
	clientID = 953667521230286888
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen
	configScreen = false
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 12

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "%player% | Minecraft is loading"
	#The second line of text under the app name
	state = "Game Starting..."
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Steal Life"
	#The Asset ID of the image to display as the small image
	smallImageKey = "minecraft-logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "A Minecraft Launcher with %mods% mods installed"
	#The buttons to display on Discord
	[[init.buttons]]
		label = "Discord"
		url = "https://steallifefr.tk/discord"

	[[init.buttons]]
		label = "Site"
		url = "https://steallifefr.tk/"

#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "%player% | Is currently lazy"
	#The seconds line of text under the app name
	state = "Chilling in the menu"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Steal Life"
	#The Asset ID of the image to display as the small image
	smallImageKey = "minecraft-logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "A Minecraft Launcher with %mods% mods installed"
	#The buttons to display on Discord
	[[main_menu.buttons]]
		label = "🎆・Discord"
		url = "https://steallifefr.tk/discord"

	[[main_menu.buttons]]
		label = "📺・Site"
		url = "https://steallifefr.tk/"

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "%player% | Is looking for a server"
	#The second line of text under the app name
	state = "Searching for friends"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Steal Life"
	#The Asset ID of the image to display as the small image
	smallImageKey = "minecraft-logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "A Minecraft Launcher with %mods% mods installed"
	#The buttons to display on Discord
	[[server_list.buttons]]
		label = "🎆・Discord"
		url = "https://steallifefr.tk/discord"

	[[server_list.buttons]]
		label = "📺・Site"
		url = "https://steallifefr.tk/"

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "%player% | Is joining a game"
	#The second line of text under the app name
	state = "Joining Game"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Steal Life"
	#The Asset ID of the image to display as the small image
	smallImageKey = "minecraft-logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "A Minecraft Launcher with %mods% mods installed"
	#The buttons to display on Discord
	[[join_game.buttons]]
		label = "🎆・Discord"
		url = "https://steallifefr.tk/discord"

	[[join_game.buttons]]
		label = "📺・Site"
		url = "https://steallifefr.tk"

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "%player% | Currently In %world%"
	#The second line of text under the app name
	state = "Playing lonely mode (Sucks)"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Steal Life"
	#The Asset ID of the image to display as the small image
	smallImageKey = "minecraft-logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "A Minecraft Launcher with %mods% mods installed"
	#The buttons to display on Discord
	[[single_player.buttons]]
		label = "🎆・Discord"
		url = "https://steallifefr.tk/discord"

	[[single_player.buttons]]
		label = "📺・Site"
		url = "https://steallifefr.tk"

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "%player% | Playing online"
	#The second line of text under the app name
	state = "Playing with %players% players"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Steal Life"
	#The Asset ID of the image to display as the small image
	smallImageKey = "minecraft-logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "A Minecraft Launcher with %mods% mods installed"
	#The buttons to display on Discord
	[[multi_player.buttons]]
		label = "🎆・Discord"
		url = "https://steallifefr.tk/discord"

	[[multi_player.buttons]]
		label = "📺・Site"
		url = "https://steallifefr.tk"

#Fallback event for disabled events
[generic]
	#The first line of text under the app name
	description = "%player% | Playing Minecraft"
	#The second line of text under the app name
	state = "%player% has voided, no more info !"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Steal Life"
	#The Asset ID of the image to display as the small image
	smallImageKey = "minecraft-logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "A Minecraft Launcher with %mods% mods installed"
	#The buttons to display on Discord
	[[generic.buttons]]
		label = "🎆・Discord"
		url = "https://steallifefr.tk/discord"

	[[generic.buttons]]
		label = "📺・Site"
		url = "https://steallifefr.tk"

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = false

	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = "%player% is in The Overworld"
		state = ""
		largeImageKey = "overworld"
		largeImageText = "In the Overworld"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = "%player% is in The Nether"
		state = ""
		largeImageKey = "nether"
		largeImageText = "In the Nether"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = "%player% is in The End"
		state = ""
		largeImageKey = "end"
		largeImageText = "In the End"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"

